# Generated by Django 5.1.5 on 2025-03-03 07:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegularRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_type', models.CharField(choices=[('new', 'New Registration'), ('registered', 'Registered')], default='new', max_length=10)),
                ('UHID', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('prefix', models.CharField(choices=[('Mr', 'Mr'), ('Miss', 'Miss'), ('Mrs', 'Mrs')], default='Mr', max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('address', models.TextField()),
                ('pin_code', models.CharField(blank=True, max_length=10, null=True)),
                ('area', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('age_years', models.IntegerField(blank=True, null=True)),
                ('age_months', models.IntegerField(blank=True, null=True)),
                ('age_days', models.IntegerField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('id_proof', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('mobile_no', models.CharField(max_length=15)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed')], max_length=10, null=True)),
                ('religion', models.CharField(default='Indian', max_length=50)),
                ('warning', models.TextField(blank=True, null=True)),
                ('mediclaim', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('reimbursement', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('dependant', models.CharField(blank=True, max_length=100, null=True)),
                ('dep_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('provisional_diagnosis', models.TextField(blank=True, null=True)),
                ('visit_date', models.DateField()),
                ('visit_time', models.TimeField(default=django.utils.timezone.now)),
                ('hospital', models.CharField(default='MIT Hospital', max_length=100)),
                ('patient_type', models.CharField(choices=[('Self', 'Self'), ('Dependent', 'Dependent')], default='Self', max_length=10)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('tariff', models.CharField(default='HOSPITAL', max_length=50)),
                ('department', models.CharField(choices=[('neurology', 'Neurology'), ('cardiology', 'Cardiology'), ('gynaecology', 'Gynaecology'), ('obstetrics', 'Obstetrics'), ('surgery', 'Surgery'), ('radiology', 'Radiology'), ('gastroenterology', 'Gastroenterology'), ('pathology', 'Pathology'), ('pharmacy', 'Pharmacy'), ('pediatrics', 'Pediatrics'), ('emergency_medicine', 'Emergency Medicine')], max_length=100)),
                ('doctor', models.CharField(blank=True, max_length=100, null=True)),
                ('ref_doctor', models.CharField(blank=True, max_length=100, null=True)),
                ('is_vip', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='patient_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
