# Generated by Django 5.1.5 on 2025-03-03 06:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_status', models.CharField(choices=[('new', 'New Registration'), ('registered', 'Registered')], max_length=15)),
                ('uhid', models.CharField(blank=True, max_length=50, null=True)),
                ('prefix', models.CharField(choices=[('Mr', 'Mr'), ('Miss', 'Miss'), ('Mrs', 'Mrs')], max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('address', models.TextField()),
                ('pin_code', models.CharField(max_length=10)),
                ('taluka', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('date_of_birth', models.DateField()),
                ('use_dob', models.BooleanField(default=False)),
                ('age_years', models.IntegerField()),
                ('age_months', models.IntegerField()),
                ('age_days', models.IntegerField()),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B-'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=10, null=True)),
                ('id_proof', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_no', models.CharField(max_length=15)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('visit_date', models.DateField()),
                ('visit_time', models.TimeField(default=django.utils.timezone.now)),
                ('hospital', models.CharField(max_length=100)),
                ('patient_type', models.CharField(choices=[('self', 'Self'), ('insurance', 'Insurance'), ('corporate', 'Corporate')], max_length=20)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('tariff', models.CharField(max_length=50)),
                ('department', models.CharField(choices=[('neurology', 'Neurology'), ('cardiology', 'Cardiology'), ('gynaecology', 'Gynaecology'), ('obstetrics', 'Obstetrics'), ('surgery', 'Surgery'), ('radiology', 'Radiology'), ('gastroenterology', 'Gastroenterology'), ('pathology', 'Pathology'), ('pharmacy', 'Pharmacy'), ('pediatrics', 'Pediatrics'), ('emergency_medicine', 'Emergency Medicine')], max_length=50)),
                ('doctor', models.CharField(max_length=100)),
                ('cabin', models.CharField(blank=True, max_length=50, null=True)),
                ('ref_doctor', models.CharField(blank=True, max_length=100, null=True)),
                ('other_doctor', models.CharField(blank=True, max_length=100, null=True)),
                ('provisional_diagnosis', models.TextField(blank=True, null=True)),
                ('visit_only', models.BooleanField(default=False)),
                ('visit_flag', models.CharField(blank=True, max_length=50, null=True)),
                ('relative_name', models.CharField(blank=True, max_length=100, null=True)),
                ('relative_address', models.TextField(blank=True, null=True)),
                ('relative_phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('relation', models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('spouse', 'Spouse'), ('sibling', 'Sibling'), ('guardian', 'Guardian')], max_length=50, null=True)),
                ('service_name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('discount_amount', models.FloatField(blank=True, null=True)),
                ('net_amount', models.FloatField(blank=True, null=True)),
                ('bill_remark', models.TextField(blank=True, null=True)),
                ('payment_mode_cash', models.BooleanField(default=False)),
                ('warning', models.TextField(blank=True, null=True)),
                ('is_mlc', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
            ],
        ),
    ]
