# Generated by Django 5.1.5 on 2025-03-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourierList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_date', models.DateField()),
                ('person_company_name', models.CharField(max_length=255)),
                ('courier_type', models.CharField(choices=[('Inward', 'Inward'), ('Outward', 'Outward')], max_length=7)),
                ('category', models.CharField(choices=[('Personal', 'Personal'), ('Company', 'Company')], max_length=8)),
                ('address', models.TextField()),
                ('contact_no', models.CharField(max_length=15)),
            ],
        ),
    ]
