# Generated by Django 5.1.5 on 2025-03-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('inward_outward', models.CharField(choices=[('Inward', 'Inward'), ('Outward', 'Outward')], max_length=10)),
                ('personal_company', models.CharField(choices=[('Personal', 'Personal'), ('Company', 'Company')], max_length=10)),
                ('received_from', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact_no', models.CharField(max_length=15)),
                ('courier_content', models.TextField()),
                ('to_department', models.CharField(max_length=100)),
                ('staff_name', models.CharField(max_length=100)),
            ],
        ),
    ]
