# Generated by Django 5.1.5 on 2025-03-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OPDBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('uhid', models.CharField(max_length=50, unique=True)),
                ('consulting_doctor', models.CharField(max_length=100)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('patient_type', models.CharField(choices=[('OPD', 'Out-Patient Department'), ('IPD', 'In-Patient Department'), ('ER', 'Emergency Room')], max_length=10)),
                ('advanced_search_option', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
