# Generated by Django 5.1.5 on 2025-03-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.CharField(max_length=255)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('patient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('uhid', models.CharField(blank=True, max_length=50, null=True)),
                ('op_ip_no', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_no', models.CharField(max_length=50, unique=True)),
                ('bill_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tds_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('wrf_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_net_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
