# Generated by Django 5.1.5 on 2025-03-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=255)),
                ('visitor_pass_collected', models.BooleanField(default=False)),
                ('out_time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
