# Generated by Django 5.1.5 on 2025-03-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_appointment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneAppointmentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('doctor', models.CharField(max_length=255)),
                ('doctor_mobile', models.CharField(max_length=15)),
                ('ref_doctor_name', models.CharField(max_length=255)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('appointment_type', models.CharField(choices=[('OPD', 'OPD'), ('IPD', 'IPD'), ('Emergency', 'Emergency')], max_length=50)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('department', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Kept', 'Kept'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending')], max_length=20)),
            ],
        ),
    ]
