# Generated by Django 5.1.5 on 2025-03-04 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OPDRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_date', models.DateField()),
                ('refund_no', models.CharField(max_length=50, unique=True)),
                ('uhid', models.CharField(max_length=50)),
                ('patient_name', models.CharField(max_length=255)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remark', models.TextField(blank=True, null=True)),
                ('opd_ipd_type', models.CharField(choices=[('OPD', 'OPD'), ('IPD', 'IPD'), ('ALL', 'ALL')], default='OPD', max_length=3)),
                ('authorization_status', models.CharField(choices=[('Pending', 'Pending'), ('Authorized', 'Authorized'), ('All', 'All')], default='Pending', max_length=10)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('All', 'All')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
