# Generated by Django 5.1.5 on 2025-03-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('uhid', models.CharField(max_length=50, unique=True)),
                ('consulting_doctor', models.CharField(max_length=255)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('patient_type', models.CharField(choices=[('OPD', 'OPD'), ('IPD', 'IPD'), ('Emergency', 'Emergency')], max_length=50)),
            ],
        ),
    ]
