# Generated by Django 5.1.5 on 2025-03-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpList',
            fields=[
                ('seq_no', models.AutoField(primary_key=True, serialize=False)),
                ('followup_date', models.DateField()),
                ('doctor_name', models.CharField(max_length=255)),
                ('patient_first_name', models.CharField(max_length=255)),
                ('patient_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('remark', models.TextField(blank=True, null=True)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('phone_appointment', models.BooleanField(default=False)),
                ('followup_call_details', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
