# Generated by Django 5.1.5 on 2025-03-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OP_patient_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=15)),
                ('uhid', models.CharField(blank=True, max_length=50, null=True)),
                ('consulting_doctor', models.CharField(blank=True, max_length=100, null=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('patient_type', models.CharField(choices=[('OPD', 'Outpatient'), ('ER', 'Emergency'), ('IPD', 'Inpatient')], max_length=10)),
                ('advance_search', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('printed', 'Printed'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
